### ISSUE TITLE
感谢分享使用GTSTK的案例，请问有处理rinex3.02或者3.04多频多系统的example吗？

### ISSUE THREAD

**Issue by bryantaoli** [libing64/gpstk_example#1]
感谢分享使用GTSTK的案例，请问有处理rinex3.02或者3.04多频多系统的example吗？

**Comment by libing64** [comment]
我没试过rinex3的 data，不过gpstk是支持Rinex 3，简单改改应该就能跑

**Comment by bryantaoli** [comment]
> 我没试过rinex3的 data，不过gpstk是支持Rinex 3，简单改改应该就能跑

好的，谢谢，我去改改
